//! `ProjectMemory` — the data this crate persists. See the crate-level
//! doc comment and `docs/project-memory-design.md` for the "why".
//!
//! Deliberately smaller than a general-purpose curated memory (no
//! freeform `key_decisions`/`errors_resolved` with narrative judgment):
//! this project's own findings this session (the prose plan degenerating
//! at both scale extremes, the typed task list rescuing the small
//! executor where prose didn't — `docs/sweep-planner-ab-2026-07-11.md`)
//! are the reason `touched_files`/`completed_signals` are built
//! deterministically from `AgentEvent`s, never by asking a small
//! executor to freely narrate what mattered. `objective`/`notes` exist
//! as fields but nothing in this crate fills them — that's the
//! lead-delegated V2 step the design doc describes, explicitly out of
//! V1's scope.

use serde::{Deserialize, Serialize};

/// A file the agent wrote or edited, deduplicated by path (only the most
/// recent touch per path survives — see [`ProjectMemory::record_touched_file`]).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TouchedFile {
    pub path: String,
    /// The tool that touched it last (`"write_file"` or `"edit_file"`).
    pub last_tool: String,
    /// RFC3339-ish timestamp string, supplied by the caller — this crate
    /// never calls a clock itself (keeps it deterministic and testable;
    /// see the crate-level "no clock" note).
    pub at: String,
}

/// A deterministically-derived signal that something got done. `source`
/// records HOW it was derived, so a future consumer can tell a
/// tool-call-pattern guess apart from a real completion event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompletedSignal {
    pub description: String,
    pub at: String,
    pub source: SignalSource,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalSource {
    /// From `AgentEvent::TaskCompleted` (the typed task list's `done`
    /// transition) — the highest-confidence source: an explicit,
    /// structured signal, not a guess.
    TaskListCompletion,
    /// Reserved for a future deterministic heuristic derived from raw
    /// tool-call sequences (e.g. an edit immediately followed by a
    /// passing test run) — not populated by this crate's V1 hook.
    ToolCallPattern,
    /// A lead/planner model wrote this, on explicit request — never
    /// generated by an unsupervised small executor (see the module doc
    /// comment). Not populated by anything in V1.
    LeadSummary,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemoryMeta {
    /// RFC3339-ish timestamp string of the last successful `save`,
    /// caller-supplied (see the crate-level "no clock" note).
    pub updated_at: Option<String>,
    /// Bumped whenever the on-disk schema changes shape — mirrors the
    /// `_meta.version` convention already used by
    /// `~/.claude/session_state/*.json`, so a future reader can tell an
    /// old file apart from a new one before trusting its shape.
    pub schema_version: u32,
}

/// One project's persisted memory. `Default` is the empty-but-valid
/// starting point `FileProjectMemoryStore::load` returns for a project
/// with no file yet.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProjectMemory {
    /// Identity — the canonicalized project root path (see
    /// `crate::project_key`). `FileProjectMemoryStore::load` has no way
    /// to check it (it doesn't receive an expected key); enforcement
    /// lives in the consumer — `braze-engine`'s `ProjectMemoryHook::new`
    /// discards a loaded memory whose `project_key` doesn't match the
    /// project it was asked for (v8 K-7), so a store accidentally
    /// pointed at the wrong file fails safe instead of injecting another
    /// project's notes into the system prompt.
    pub project_key: String,
    pub objective: Option<String>,
    pub touched_files: Vec<TouchedFile>,
    pub completed_signals: Vec<CompletedSignal>,
    pub notes: Option<String>,
    pub meta: MemoryMeta,
}

impl ProjectMemory {
    /// Caps `touched_files` — same reasoning as
    /// `~/.claude/session_state`'s `important_files` (unbounded, but
    /// this is capped because unlike that hand-curated file, this one
    /// is machine-written and could otherwise grow every session
    /// forever). Oldest entries drop first.
    const MAX_TOUCHED_FILES: usize = 50;
    /// Same reasoning as `completed_tasks`' 50-item cap in
    /// `~/.claude/session_state` — smaller here because V1 only
    /// populates this from the highest-confidence source
    /// (`TaskListCompletion`), so entries are rarer and more valuable
    /// individually; no archival tier like that system's
    /// `archived_tasks` in V1.
    const MAX_COMPLETED_SIGNALS: usize = 30;

    pub fn new(project_key: impl Into<String>) -> Self {
        Self {
            project_key: project_key.into(),
            meta: MemoryMeta {
                schema_version: 1,
                ..MemoryMeta::default()
            },
            ..Self::default()
        }
    }

    /// Records that `path` was touched by `tool` at `at`. Dedup by
    /// path: an existing entry for the same path is dropped and
    /// re-appended at the end (most-recent-last), not merged in place —
    /// this keeps `touched_files`' order meaningful (recency) without a
    /// separate ordering field.
    pub fn record_touched_file(
        &mut self,
        path: impl Into<String>,
        tool: impl Into<String>,
        at: impl Into<String>,
    ) {
        let path = path.into();
        self.touched_files.retain(|f| f.path != path);
        self.touched_files.push(TouchedFile {
            path,
            last_tool: tool.into(),
            at: at.into(),
        });
        if self.touched_files.len() > Self::MAX_TOUCHED_FILES {
            self.touched_files.remove(0);
        }
    }

    /// Records a completion signal. Empty descriptions are silently
    /// dropped (nothing meaningful to remember) rather than erroring —
    /// this is called from a hook's `on_event`, which must never fail a
    /// turn over a memory-bookkeeping edge case.
    ///
    /// Dedup by (description, source), keeping the latest occurrence
    /// (same move-to-end shape as [`Self::record_touched_file`]): the
    /// task list already suppresses Done→Done re-reports at the source
    /// (v8 K-6, `braze-engine`'s `TaskList::update`), but this cap-guarded
    /// list is the last line of defense — with `MAX_COMPLETED_SIGNALS`
    /// evicting oldest-first, letting duplicates through would push a
    /// *distinct* old signal out for every copy of a repeated one.
    pub fn record_completed_signal(
        &mut self,
        description: impl Into<String>,
        source: SignalSource,
        at: impl Into<String>,
    ) {
        let description = description.into();
        if description.trim().is_empty() {
            return;
        }
        self.completed_signals
            .retain(|s| !(s.description == description && s.source == source));
        self.completed_signals.push(CompletedSignal {
            description,
            source,
            at: at.into(),
        });
        if self.completed_signals.len() > Self::MAX_COMPLETED_SIGNALS {
            self.completed_signals.remove(0);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn record_touched_file_dedups_by_path_keeping_the_latest() {
        let mut memory = ProjectMemory::new("proj");
        memory.record_touched_file("src/main.rs", "write_file", "t1");
        memory.record_touched_file("src/lib.rs", "edit_file", "t2");
        memory.record_touched_file("src/main.rs", "edit_file", "t3");

        assert_eq!(memory.touched_files.len(), 2, "duplicate path collapses to one entry");
        assert_eq!(memory.touched_files[0].path, "src/lib.rs");
        assert_eq!(memory.touched_files[1].path, "src/main.rs");
        assert_eq!(memory.touched_files[1].last_tool, "edit_file");
        assert_eq!(memory.touched_files[1].at, "t3", "re-touch moves to most-recent");
    }

    #[test]
    fn record_touched_file_caps_and_drops_the_oldest() {
        let mut memory = ProjectMemory::new("proj");
        for i in 0..(ProjectMemory::MAX_TOUCHED_FILES + 5) {
            memory.record_touched_file(format!("file{i}.rs"), "write_file", "t");
        }
        assert_eq!(memory.touched_files.len(), ProjectMemory::MAX_TOUCHED_FILES);
        assert_eq!(
            memory.touched_files[0].path, "file5.rs",
            "the 5 oldest entries must have been dropped"
        );
    }

    #[test]
    fn record_completed_signal_drops_empty_descriptions() {
        let mut memory = ProjectMemory::new("proj");
        memory.record_completed_signal("   ", SignalSource::TaskListCompletion, "t1");
        assert!(memory.completed_signals.is_empty());
    }

    #[test]
    fn record_completed_signal_caps_and_drops_the_oldest() {
        let mut memory = ProjectMemory::new("proj");
        for i in 0..(ProjectMemory::MAX_COMPLETED_SIGNALS + 3) {
            memory.record_completed_signal(
                format!("task {i}"),
                SignalSource::TaskListCompletion,
                "t",
            );
        }
        assert_eq!(memory.completed_signals.len(), ProjectMemory::MAX_COMPLETED_SIGNALS);
        assert_eq!(memory.completed_signals[0].description, "task 3");
    }
}
